name: CI

on:
  pull_request:
    branches:
      - "main"
      - "dev"

jobs:

  code-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Lua & luacheck
        run: |
          sudo apt-get update
          sudo apt-get install -y luarocks
          sudo luarocks install luacheck
      - name: Run luacheck
        run: luacheck ./

  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Install stylua
        run: cargo install stylua
      - name: Run stylua
        run: stylua --check ./
