name: CI

on:
  pull_request:
    branches:
      - "main"
      - "dev"

jobs:

  code-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install lua & luacheck
        run: |
          sudo apt-get update
          sudo apt-get install -y luarocks
          sudo luarocks install luacheck
      - name: Run luacheck
        run: luacheck ./

  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Install stylua
        run: cargo install stylua
      - name: Run stylua
        run: stylua --check ./

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install lua
        run: |
          sudo apt-get update
          sudo apt-get install -y luarocks
      - name: Run testsuite
        run: make test

  coverage:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: actions/checkout@v3
      - name: Install lua
        run: |
          sudo apt-get update
          sudo apt-get install -y luarocks
          sudo luarocks install luacov
      - name: Run tests with coverage
        run: make coverage
      - name: Read coverage %
        id: coverage
        run: |
          coverage=$(awk '/^Total/ {print $4}' luacov.report.out | tr -d '%')
          echo "coverage=$coverage" >> $GITHUB_OUTPUT
      - name: Fail if coverage too low
        if: ${{ steps.coverage.outputs.coverage < 95 }}
        run: |
          echo "Coverage too low: ${{ steps.coverage.outputs.coverage }}%"
          exit 1
