name: Upload new release

on:
  push:
    branches:
      - "main"

jobs:

  upload-release:
    runs-on: ubuntu-latest
    env:
      MOD_UPLOAD_API_KEY: ${{ secrets.MOD_UPLOAD_API_KEY }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install requests
      - name: Create zip
        run: make archive
      - name: Upload new release
        run: python .github/upload.py *.zip
