name: Validate release

on:
  pull_request:
    branches:
      - "main"

jobs:

  validate-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Get previous version
        id: get_previous_version
        run: |
          git fetch origin main
          prev_version=$(git show origin/main:info.json | jq -r '.version')
          echo "version=$prev_version" >> $GITHUB_OUTPUT
      - name: Validate all files
        run: python .github/validate.py ${{ steps.get_previous_version.outputs.version }}
